### ISSUE TITLE
save game feature

### ISSUE THREAD

**Issue by ulpian** [watabou/pixel-dungeon#44]
was wondering if this is simple enough to implement a quick-dirty implementation to save assets and landscape and then load these when playing the game, I am running this on desktop so i dont need graphics can do from cli

**Comment by gabea1** [comment]
get remixed pixel dongeon

**Comment by markozajc** [comment]
That would've ruined the whole point of this _Rougelike_ game. If you want to save, you either have to use a data backup program (like Titanium Backup) or use another implementation of Pixel Dungeon (like Soft Pixel dungeon or as  @gabea1 said, Remixed Pixel Dungeon). Note that that's consider cheating because what differentiates Rougelike games from other games is permanent death.

**Comment by ulpian** [comment]
cool
