### ISSUE TITLE
how can i import this into unity

### ISSUE THREAD

**Issue by Vortetty** [watabou/pixel-dungeon#81]
i need to import this into unity so i can add stuff

**Comment by TheYsconator** [comment]
Why do you want to import it into Unity? Because, assuming you want to have it 'natively' (and not just solve it by loading a Java wrapper into Unity), that's going to be a lot of work.

If you want to study Unity, I recommend other projects, that are already made for Unity.

If you want to mod this game, I recommend you to just mod it as-is. There are many other mods, and Java isn't that difficult, so you should be able to figure that out.

If you want to port the game to other systems, you could try using libgdx instead of Unity.

If you really want to import it in Unity, without using some sort of Java executer, I can think of no other way than just translating the files. What you have to keep in mind, though, is that the world editor of Unity would not really work, as most floors are completely randomly generated. So I doubt using Unity will make modding any easier.

Anyway, if you have further questions, you can always poke me. For in the future: I doubt this is the best place to ask this kind of question.

**Comment by Vortetty** [comment]
ok, i just thought it might be easier to add items through there, will use java though
