### ISSUE TITLE
Getting stuck

### ISSUE THREAD

**Issue by pjotrek-b** [watabou/pixel-dungeon#86]
Is it possible to get stuck in a dungeon level?

It's happened to me several times in a row now that I can't take the stairs up ("You can't leave yet!"), but there's nowhere else to go. Stairs downwards only lead to a room with some item, but no further doors/rooms.

Unless there's somewhere I can "fall" down to a new level, I'm stuck.

Is this intentionally, or am I overlooking something?
Thanks in advance :)

> Version is 0.7.0a (from F-Droid)

**Comment by TheYsconator** [comment]
Well, that would've been a major bug now, wouldn't it? Perhaps too major?

Did you try searching the walls of that room on the second floor for a hidden door?

**Comment by pjotrek-b** [comment]
Major bug: Thought exactly the same :smile:
Therefore I assumed I'm missing something.

I think I checked everything, but couldn't find any hidden doors, etc. Sorry I'm new to the game.
Will check more thoroughly in the future then.

**Comment by TheYsconator** [comment]
Haha no worries! (You don't wanna know for how long I've been stuck there the first time I played the game. xD)

Anyway; as a heads up (and unrelated): if you're new to this game, I'd recommend Shattered Pixel Dungeon. Don't get me wrong: Pixel Dungeon is a fine game, but due to a lack of support in recent years (Pixel Dungeon is no longer supported by its developer), it is currently more of a highly influential 'the original' rather than 'the best one to begin playing with'. There are quite some good mods out there, and I do recommend you to try those out as well. In my opinion (not to promote one mod over another - you should try all 'well known mods'), Shattered Pixel Dungeon is currently best for new players. It is actively maintained, well balanced, and it doesn't stray too far from the original. Completing the original is generally considered to be more difficult than completing Shattered.

I know you didn't ask for that, but I thought I'd give you as a new player a heads up.

Also; if you want to discuss your wins/ strategy/ general discussions/ gameplay suggestions: Reddit is the place for that. You can find all Pixel Dungeon mods here: [https://www.reddit.com/r/PixelDungeon](https://www.reddit.com/r/PixelDungeon).

Enjoy! (I beat Shattered in about 250 tries; poke me on Reddit if you want to show off.)

**Comment by Sarius997** [comment]
just a quick note: concluding from the provided version number (0.7.0a while vanilla pd is at 1.9.2a) and the fact, that I can only find Shattered Pixel Dungeon on f-droid, I assume that you ( @pjotrek-b ) are already playing Shattered Pixel Dungeon and if this is the case, you should report bugs (if you find any) at the corresponding github repository: https://github.com/00-Evan/shattered-pixel-dungeon

I wish you good luck for your future runs (especially more luck with finding the hidden doors)

PS.: as @TheYsconator mentioned, the PixelDungeon subreddit is a great place if you seek advice or basically everything related to pixel dungeon
